USE CEA
GO

CREATE TABLE PAIS
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
COD_PAIS CHAR(2) NOT NULL,
NOMBRE_PAIS VARCHAR (50) NOT NULL,
)
GO

CREATE TABLE CIUDAD
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_PAIS INT NOT NULL,
COD_CIUDAD CHAR(2) NOT NULL,
NOMBRE_CIUDAD VARCHAR(50) NOT NULL
)
GO

CREATE TABLE CEA
(
	ID INT IDENTITY not null primary key,
	COD_CEA varchar(10) not null,
	NOMBRE_CEA varchar (200) not null,
	CODIGO_IDENTIFICACION varchar(13) not null,
	ID_PAIS INT NOT NULL,
	ID_CIUDAD INT NOT NULL,
	CONSTRAINT FK_CEA_PAIS FOREIGN KEY (ID_PAIS)  REFERENCES PAIS (ID),
	CONSTRAINT FK_CEA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID)
)
GO

CREATE TABLE CEA_SEDE
(
ID INT IDENTITY NOT NULL PRIMARY KEY,
ID_CEA INT NOT NULL,
NOMBRE_SEDE VARCHAR(200) NOT NULL,
ID_CIUDAD INT NOT NULL,
CONSTRAINT FK_CEA_SEDE_CEA FOREIGN KEY (ID_CEA) REFERENCES CEA (ID),
CONSTRAINT FK_CEA_SEDE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID)
)
GO

CREATE TABLE CEA_USUARIO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
NOMBRE_USUARIO VARCHAR(100) NOT NULL,
CARGO VARCHAR(50),
PERFIL VARCHAR(100) NOT NULL,
CONSTRAINT FK_CEA_USUARIO_CEA_SEDE FOREIGN KEY (ID_CEA_SEDE) REFERENCES CEA_SEDE(ID)
)

GO

CREATE TABLE CEA_CURSO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
COD_CURSO VARCHAR(20) NOT NULL,
NOMBRE_CURSO VARCHAR(20) NOT NULL,
CONSTRAINT FK_CEA_CURSO_CEA_SEDE FOREIGN KEY(ID_CEA_SEDE) REFERENCES CEA_SEDE(ID)
)
GO

CREATE TABLE CEA_INSTRUCTOR
(
ID INT NOT NULL PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
COD_INSTRUCTOR VARCHAR(10) NOT NULL,
NOMBRE_INSTRUCTOR VARCHAR(100) NOT NULL,
CARGO VARCHAR(50) NULL,
ACTIVO BIT,
CONSTRAINT FK_CEA_INSTRUCTOR_CEA_SEDE FOREIGN KEY (ID_CEA_SEDE) REFERENCES CEA_SEDE(ID)
)
GO

CREATE TABLE CEA_INSTRUCTOR_CURSO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_CURSO INT NOT NULL,
ID_CEA_INSTRUCTOR INT NOT NULL,
CONSTRAINT FK_CEA_INSTRUCTOR_CURSO_CEA_CURSO FOREIGN KEY (ID_CEA_CURSO) REFERENCES CEA_CURSO(ID),
CONSTRAINT FK_CEA_INSTRUCTOR_CURSO_CEA_INSTRUCTOR FOREIGN KEY (ID_CEA_INSTRUCTOR) REFERENCES CEA_INSTRUCTOR(ID)
)
GO

CREATE TABLE CEA_VEHICULO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
COD_VEHICULO VARCHAR(20) NOT NULL,
TIPO_VEHICULO VARCHAR(100) NULL,
CONSTRAINT FK_CEA_VEHICULO_CEA_SEDE FOREIGN KEY (ID_CEA_SEDE) REFERENCES CEA_SEDE(ID)
)
GO

CREATE TABLE CEA_ESTUDIANTE
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
IDENTIFICACION VARCHAR(13),
NOMBRE_ESTUDIANTE VARCHAR(100),
TELEFONO VARCHAR(20),
ACTIVO BIT,
CONSTRAINT FK_CEA_ESTUDIANTE_CEA_SEDE FOREIGN KEY (ID_CEA_SEDE) REFERENCES CEA_SEDE(ID)
)
GO

CREATE TABLE CEA_ESTUDIANTE_CURSO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_CURSO INT NOT NULL,
ID_CEA_ESTUDIANTE INT NOT NULL,
CONSTRAINT FK_CEA_ESTUDIANTE_CURSO_CEA_CURSO FOREIGN KEY (ID_CEA_CURSO) REFERENCES CEA_CURSO(ID),
CONSTRAINT FK_CEA_ESTUDIANTE_CURSO_CEA_ESTUDIANTE FOREIGN KEY (ID_CEA_ESTUDIANTE) REFERENCES CEA_ESTUDIANTE (ID)
)
GO

CREATE TABLE CEA_DISP_INSTRUCTOR
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_INSTRUCTOR INT NOT NULL,
FECHA_DISPONIBILIDAD DATETIME NOT NULL,
HORA_INICIO TIME NOT NULL,
HORA_FIN TIME NOT NULL,
ID_CEA_CURSO INT NOT NULL,
ESTADO CHAR(2) NOT NULL DEFAULT 'D',
FECHA_CREACION DATETIME,
USUARIO_CREACION INT NOT NULL,
FECHA_MODIFICACION DATETIME NULL,
USUARIO_MODIFICACION INT NULL,
CONSTRAINT FK_CEA_DISP_INSTRUCTOR_CEA_INSTRUCTOR FOREIGN KEY (ID_INSTRUCTOR) REFERENCES CEA_INSTRUCTOR(ID),
CONSTRAINT FK_CEA_DISP_INSTRUCTOR_CEA_CURSO FOREIGN KEY (ID_CEA_CURSO) REFERENCES CEA_CURSO(ID)
)
GO

CREATE TABLE CEA_DISP_VEHICULO
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_VEHICULO INT NOT NULL,
FECHA_DISPONIBILIDAD DATETIME NOT NULL,
HORA_INICIO TIME NOT NULL,
HORA_FIN TIME NOT NULL,
ESTADO CHAR(2) NOT NULL DEFAULT 'D',
FECHA_CREACION DATETIME,
USUARIO_CREACION INT NOT NULL,
FECHA_MODIFICACION DATETIME NULL,
USUARIO_MODIFICACION INT NULL
)
GO

CREATE TABLE CEA_AGENDA
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_CEA_SEDE INT NOT NULL,
ID_ESTUDIANTE INT NULL,
FECHA_AGENDA DATETIME NOT NULL,
HORA_INICIO TIME NOT NULL,
HORA_FIN TIME NOT NULL,
ID_CEA_DISP_INSTRUCTOR INT NULL,
ID_CEA_CURSO INT NOT NULL,
ID_CEA_DIS_VEHICULO INT NULL,
NUM_HORAS TINYINT NULL,
ESTADO CHAR(2) NOT NULL DEFAULT 'D',
FECHA_CREACION DATETIME,
USUARIO_CREACION INT NOT NULL,
FECHA_MODIFICACION DATETIME NULL,
USUARIO_MODIFICACION INT NULL,
CONSTRAINT FK_CEA_AGENDA_CEA_SEDE FOREIGN KEY (ID_CEA_SEDE) REFERENCES CEA_SEDE(ID),
CONSTRAINT FK_CEA_AGENDA_CEA_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES CEA_ESTUDIANTE(ID),
CONSTRAINT FK_CEA_AGENDA_CEA_DISP_INSTRUCTOR FOREIGN KEY (ID_CEA_DISP_INSTRUCTOR) REFERENCES CEA_DISP_INSTRUCTOR(ID),
CONSTRAINT FK_CEA_AGENDA_CEA_DISP_VEHICULO FOREIGN KEY (ID_CEA_DIS_VEHICULO) REFERENCES CEA_DISP_VEHICULO(ID),
CONSTRAINT FK_CEA_AGENDA_CEA_CURSO FOREIGN KEY (ID_CEA_CURSO) REFERENCES CEA_CURSO(ID)
)
GO

CREATE TABLE CEA_CANCELACION_AGENDA
(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ID_AGENDA INT NOT NULL,
ID_ESTUDIANTE INT NOT NULL,
FECHA_CANCELACION DATETIME,
MOTIVO_CANCELACION VARCHAR(500) NOT NULL,
FECHA_CREACION DATETIME,
USUARIO_CREACION INT NOT NULL,
CONSTRAINT FK_CEA_CANCELACION_AGENDA_CEA_AGENDA FOREIGN KEY(ID_AGENDA) REFERENCES CEA_AGENDA(ID),
CONSTRAINT FK_CEA_CANCELACION_AGENDA_CEA_ESTUDAINTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES CEA_ESTUDIANTE(ID)
)





